### ISSUE TITLE
wootingHE  error 255 -keyboard constantly connects and disconnects  to wootility

### ISSUE THREAD

**Issue by BlackburnUTG** [WootingKb/wootility-issues#140]
yesterday my keyboard had a strange behavior - when I switched profiles with mode hotkeys (A1,A2,A3, Mode) - it switched to default rgb profile (I don't even have it my keyboard memory, and in wootility). I could switch to my profiles only from wootility, not from wooting hotkeys.
today I have this error in wootility
Error (255)
And my keyboard constantly connects and disconnects  to wootility

![изображение](https://user-images.githubusercontent.com/19798113/153190519-15698f7f-2378-4ee7-88d4-eb05e7aa34e7.png)

Win10x64
motherboard: Asrock Fatal1ty B450 Gaming K4

wootility v4.3.8-beta
wootingHE firmware v2.4.8

**Keyboard Type**
Wooting one or two + language

**Comment by simon-wh** [comment]
Have you tried performing a restore under the troubleshoot section of settings? You can duplicate your device profiles in wootility beforehand so you can put them back on after it has reset.

**Comment by BlackburnUTG** [comment]
unplugging and replugging in my keyboard fixed it

**Comment by Rocky04** [comment]
I assume this may comes down to problems with the latest firmware and especially Ryzen systems.

**Comment by mikey-dg** [comment]
I had some kind of related issue with this firmware update (W2HE, Firmware v2.4.8, Wootility v4.3.8), where the Wootility lost connectivity to the keyboard, so I re-plugged the keyboard, the Wootility connected fine, but all keyboard mappings were effectively empty except for the A1-3 and Mode keys despite showing the mappings normally the Remap tab.  That is, pressing any key except the four profile keys would do nothing in any context, effectively disabling the keyboard.  Re-plugging the keyboard again or switching profiles in the Wootility did not resolve it.

I backed up the profiles, did a restore, re-loaded the profiles, and that seemed to fix it, but that's a pretty significant (and momentarily concerning) issue for a firmware update!

Unfortunately I didn't think to try remapping a key and saving to keyboard, so maybe that alone would have resolved it?

**Comment by lsascha** [comment]
i am using wootility-lekker-beta and just got an update notification when i started the application. After the update it also asked for a firmware update which i did.

But now i can't really configure the keyboard anymore because it completely crashes the keyboard. (means, all lights are at its brightest and no keypress is recognized anymore.)

It seems as if it crashes, restarts the keyboard, crashes again and then the keyboard is unusable.

![BjRpM9aZKW](https://user-images.githubusercontent.com/4083570/153724754-abca2c01-2b25-4d51-8fc7-e9f072abd47c.png)

Only disconnecting and reconnecting the keyboard helps.

It only crashes when using the wootility though, so its at least not completely unusable.

Only error entry in the logs i could find is this:
```
[2022-02-12 19:45:11.824] [error] Failed initProfiles on device  Error: Command Response received result ERROR (255)
    at Nt.validateResponse (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:176737)
    at Nt.get body [as body] (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:176420)
    at pa.getKeymapLayer (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:192994)
    at async pa.getKeymapLayers (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:193245)
    at async $a.initProfiles (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:271704)
    at async hl.initProfiles (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:282037)
    at async yl.startDeviceInit (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:287136)
    at async ga.deviceEventHandler [as dispatcher] (C:\Users\Me\AppData\Local\Programs\wootility-lekker-beta\resources\app.asar\js\app-bundle.js:1:284979)
[2022-02-12 19:45:11.825] [info]  device disconnect
[2022-02-12 19:45:11.825] [info]  device disconnect
[2022-02-12 19:45:11.826] [debug] {}
[2022-02-12 19:45:11.826] [info]  Device disconnected 3 id: 32527413821
[2022-02-12 19:45:13.725] [debug] Searching for devices
[2022-02-12 19:45:13.803] [debug] Found device  WOOTING_TWO_HE
[2022-02-12 19:45:13.804] [debug] Ensuring there's a valid connection
[2022-02-12 19:45:13.804] [debug] Queueing Command  Ping
[2022-02-12 19:45:13.818] [debug] Successfully pinged device
[2022-02-12 19:45:13.818] [debug] Queueing Command  GetSerial
[2022-02-12 19:45:13.834] [debug] Queueing Command  GetSerial
[2022-02-12 19:45:13.850] [debug] Queueing Command  GetDeviceConfig
[2022-02-12 19:45:13.885] [debug] Queueing Command  GetVersion
[2022-02-12 19:45:13.907] [debug] Queueing Command  GetCurrentKeyboardProfileIndex
[2022-02-12 19:45:13.946] [debug] Queueing Command  GetDeviceConfig
[2022-02-12 19:45:13.985] [debug] Queueing Command  GetSerial
[2022-02-12 19:45:14.006] [debug] Loading Color profile  0
[2022-02-12 19:45:14.006] [debug] Queueing Command  GetRgbProfileCore
[2022-02-12 19:45:14.529] [debug] Firmware Update info result:  { latestFirmwareVersion: '2.4.8', updateRequired: false }
[2022-02-12 19:45:15.884] [info]  true
[2022-02-12 19:45:15.884] [info]  device disconnect
[2022-02-12 19:45:15.885] [info]  device disconnect
[2022-02-12 19:45:15.885] [debug] Attempt to remove device that was already gone
[2022-02-12 19:45:15.885] [debug] {}
[2022-02-12 19:45:15.886] [debug] Waiting for task to finish...
[2022-02-12 19:45:15.886] [info]  Device disconnected 3 id: 32527413821
[2022-02-12 19:45:15.906] [debug] Waiting for task to finish...
[2022-02-12 19:45:15.906] [error] Error with sendCommandWithResponse with command 50 GetRgbProfileCore Error: could not read from HID device
[2022-02-12 19:45:15.956] [error] Failed initProfiles on device  Error: could not read from HID device
[2022-02-12 19:45:17.723] [debug] Searching for devices
[2022-02-12 19:45:19.717] [debug] Searching for devices
[2022-02-12 19:45:21.719] [debug] Searching for devices
[2022-02-12 19:45:23.728] [debug] Searching for devices
[2022-02-12 19:45:25.730] [debug] Searching for devices
[2022-02-12 19:45:26.014] [debug] Attempting to resume service
[2022-02-12 19:45:26.016] [debug] Service not allowed to resume, pausing...
```

**Comment by denis-roy** [comment]
+1
Experiencing the exact same issue in the exact same context as @lsascha

**Comment by PastaJ36** [comment]
Wanted to let you guys know we're onto this issue and probably know where it's from.  Pretty unlucky timing because Simon is on a (well deserved) holiday until the end of this week. I'm hoping to be able to release a hotfix / rollback the update this week, but I might have to wait to release a real fix start of next week

**Comment by PastaJ36** [comment]
We've released a fix for this issue, full details here: https://www.notion.so/wooting-technologies/v4-3-10-beta-ee79f0eb606c4c18b7dfb3fb05c9f781

Thanks everyone here for helping us identify this issue 👍
