### ISSUE TITLE
Gamepad response tab crash

### ISSUE THREAD

**Issue by LazyBoot** [WootingKb/wootility-issues#291]
**Describe the bug**
Trying to access the Gamepad Response tab crashes Wootility (both web and desktop)

**To Reproduce**
1. Enabled xbox gamepad mode
2. Selected the default "racing" profile
3. Select the "Gamepad Response" tab (this is where the error happens)

**Screenshots / Video**
Error message from web (a similar one happens on desktop too):
```
TypeError: Cannot read properties of undefined (reading 'value')
    at https://wootility.io/assets/index-5f2b87f4.js:1361:6099
    at Array.map (<anonymous>)
    at GamepadTesterInputState (https://wootility.io/assets/index-5f2b87f4.js:1361:5967)
    at oh (https://wootility.io/assets/index-5f2b87f4.js:34:54035)
    at Rj (https://wootility.io/assets/index-5f2b87f4.js:36:8987)
    at Qj (https://wootility.io/assets/index-5f2b87f4.js:36:934)
    at Kj (https://wootility.io/assets/index-5f2b87f4.js:36:853)
    at yj (https://wootility.io/assets/index-5f2b87f4.js:34:93687)
    at https://wootility.io/assets/index-5f2b87f4.js:34:39837
    at Kr.unstable_runWithPriority (https://wootility.io/assets/index-5f2b87f4.js:26:4215)
    at cg (https://wootility.io/assets/index-5f2b87f4.js:34:39523)
    at fg (https://wootility.io/assets/index-5f2b87f4.js:34:39776)
    at gg (https://wootility.io/assets/index-5f2b87f4.js:34:39709)
    at Ig (https://wootility.io/assets/index-5f2b87f4.js:34:90092)
    at zh (https://wootility.io/assets/index-5f2b87f4.js:34:58849)
    at https://wootility.io/assets/index-5f2b87f4.js:1361:8572
    at Xr (https://wootility.io/assets/index-5f2b87f4.js:730:2442)
```

**Desktop (please complete the following information):**
 - OS: Windows 10

Wootility v4.6.21
Wooting 60HE+ (iso layout)
Firmware 2.8.1

**Comment by simon-wh** [comment]
Hey, sorry for keeping you waiting 😅.

We've made a patch for this issue for the next Wootility v5 beta release that I'm aiming to get out today. So check-out v5.0.0-beta.3 when it's ready to see if you're still having issues
